### ISSUE TITLE
Synchronous Redis

### ISSUE THREAD

**Issue by telemmaite** [duyixian1234/fastapi-redis-session#1]
Hello, I like the simplicity of the implementation, good job!

My only issue is that the Redis client is the **non-async version**.
FastAPI is async API any synchronous action will block the event loop, thus blocking other concurrent request/responses.

There are some interesting details here about (async def or just def)
https://fastapi.tiangolo.com/async/#path-operation-functions

**Comment by duyixian1234** [comment]
I'm sorry that I ignored this issue for about 20 days（I didn't get any issue of my projects before）.

For this issue, it's a good topic about asyncio Redis client. 

I use synchronous Redis client because it's familiar to me. I didn't use any asyncio Redis client for Python before（I use flask and gunicorn for main projects）. Is there any asyncio redis client implementation which is stable and well maintenaned? I find one named asyncio-redis.

Meanwhile I think Redis is fast enough. Maybe I could make an asyncio version and compare their performance.

**Comment by telemmaite** [comment]
I would go for https://github.com/aio-libs/aioredis. Also you can check https://github.com/madkote/fastapi-plugins

**Comment by wiseaidev** [comment]
Hey everyone, [just released](https://pypi.org/project/aioredis-fastapi/) an asynchronous version that is compatible with aioredis. It needs some unit tests, will be working on it. But, if you are interested you can check out the project on:

- [Github](https://github.com/wiseaidev/aioredis_fastapi).
- [Pypi](https://pypi.org/project/aioredis-fastapi/).
